"""Generate a simple PDF summary for a product passport."""
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor


def build_passport_pdf(product):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    y = height - 30 * mm

    c.setFillColor(HexColor('#0d6efd'))
    c.setFont('Helvetica-Bold', 18)
    c.drawString(25 * mm, y, 'TracePass — Digital Product Passport')
    y -= 12 * mm

    c.setFillColor(HexColor('#000000'))
    c.setFont('Helvetica-Bold', 14)
    c.drawString(25 * mm, y, product.name or 'Product')
    y -= 8 * mm

    c.setFont('Helvetica', 11)
    lines = [
        f'Passport Code: {product.passport_code}',
        f'Status: {product.status}',
        f'Compliance: {product.compliance_status}',
        f'Category: {product.category or "—"}',
        f'Brand / Model: {(product.brand or "—")} / {(product.model or "—")}',
        f'Origin: {product.origin_country or "—"}',
        f'Manufacturer: {product.manufacturer.name if product.manufacturer else "—"}',
        f'Published: {product.published_at.strftime("%d %b %Y") if product.published_at else "—"}',
    ]
    for line in lines:
        c.drawString(25 * mm, y, line)
        y -= 7 * mm

    y -= 5 * mm
    c.setFont('Helvetica-Bold', 12)
    c.drawString(25 * mm, y, 'Batches')
    y -= 7 * mm
    c.setFont('Helvetica', 10)
    batches = product.batches.all()
    if not batches:
        c.drawString(25 * mm, y, 'No batches recorded.')
        y -= 6 * mm
    for b in batches[:15]:
        c.drawString(25 * mm, y, f'- {b.batch_no} | {b.manufacture_date or "n/a"} | {b.production_location or ""}')
        y -= 6 * mm
        if y < 30 * mm:
            c.showPage()
            y = height - 25 * mm

    y -= 4 * mm
    c.setFont('Helvetica-Bold', 12)
    c.drawString(25 * mm, y, 'Materials')
    y -= 7 * mm
    c.setFont('Helvetica', 10)
    for m in product.materials.all()[:15]:
        name = m.material.name if m.material else '—'
        pct = f' ({m.percentage}%)' if m.percentage else ''
        c.drawString(25 * mm, y, f'- {name}{pct}')
        y -= 6 * mm

    y -= 4 * mm
    if y < 40 * mm:
        c.showPage()
        y = height - 25 * mm
    c.setFont('Helvetica-Bold', 12)
    c.drawString(25 * mm, y, 'Certificates')
    y -= 7 * mm
    c.setFont('Helvetica', 10)
    for cert in product.certificates.all()[:10]:
        c.drawString(25 * mm, y, f'- {cert.cert_type} | {cert.issuer or "n/a"} | exp {cert.expiry_date or "—"}')
        y -= 6 * mm

    y -= 10 * mm
    c.setFont('Helvetica-Oblique', 8)
    c.setFillColor(HexColor('#666666'))
    c.drawString(25 * mm, 15 * mm, 'Generated by TracePass — Asif Raza | 0312-2626792')

    c.save()
    buffer.seek(0)
    return buffer
